#!/usr/bin/env python3
"""
new_integration.py - scaffold a multi-session (or composite) integration folder.

Creates  {target}/integrations/{target_id} {span} v{N}/  containing empty
PI Process/, PI Magic/ and a Results/ folder, plus a filled-in integration.toml
whose member-session list is selected for you from the target's session folders.

Dry run by default — it shows which sessions it would include; pass --apply to
actually create the folder.

    python3 new_integration.py --target "M 81 Bodes Galaxy" --span 2026
    python3 new_integration.py --target "M 81 Bodes Galaxy" --span 2026 \\
        --rig "RASA8 ASI2600MCAir" --version 2 --apply
    python3 new_integration.py --target "M 81 Bodes Galaxy" --span all --apply

Then do the integration in PixInsight inside that folder and re-run ingest.py.
"""
import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import astro_config   # noqa: E402

SESSION_RE = re.compile(
    r"^(?P<target>[A-Za-z0-9_+\-]+)\s+(?P<scope>\S+)\s+(?P<sensor>\S+)\s+"
    r"(?P<date>\d{4}-\d{2}-\d{2})$")


def find_target(target_name, libraries):
    """Return the target folder path across the configured libraries, or None."""
    for lib in libraries:
        p = os.path.join(lib["path"], target_name)
        if os.path.isdir(p):
            return p
    return None


def span_matches(date, span):
    """True if a YYYY-MM-DD date falls within a span: '2026', '2024-2026', 'all'."""
    if span == "all":
        return True
    year = date[:4]
    m = re.fullmatch(r"(\d{4})-(\d{4})", span)
    if m:
        return m.group(1) <= year <= m.group(2)
    return year == span


def main():
    ap = argparse.ArgumentParser(
        description="Scaffold a multi-session integration folder + manifest.")
    ap.add_argument("--target", required=True,
                    help="target folder name, e.g. 'M 81 Bodes Galaxy'")
    ap.add_argument("--span", required=True,
                    help="'2026' | a range like '2024-2026' | 'all'")
    ap.add_argument("--version", type=int, default=1, help="integration version (default 1)")
    ap.add_argument("--rig", default="",
                    help="limit members to one rig, e.g. 'RASA8 ASI2600MCAir'")
    ap.add_argument("--apply", action="store_true",
                    help="actually create the folder (default: preview only)")
    ap.add_argument("--config", default=None,
                    help="path to config.toml (default: next to this script)")
    args = ap.parse_args()

    libraries = astro_config.load_libraries(args.config)
    tpath = find_target(args.target, libraries)
    if not tpath:
        sys.exit(f"Target folder not found in any configured library: {args.target}")

    # Select member sessions from the target's session folders.
    members, rigs = [], set()
    for sname in sorted(os.listdir(tpath)):
        if sname == "integrations" or sname.startswith((".", "_")):
            continue
        if not os.path.isdir(os.path.join(tpath, sname)):
            continue
        m = SESSION_RE.match(sname)
        if not m or not span_matches(m.group("date"), args.span):
            continue
        rig = f"{m.group('scope')} {m.group('sensor')}"
        if args.rig and rig != args.rig:
            continue
        members.append(sname)
        rigs.add(rig)

    if not members:
        sys.exit(f"No sessions matched span '{args.span}'"
                 + (f" / rig '{args.rig}'" if args.rig else "")
                 + f" under {args.target}.")

    target_id = SESSION_RE.match(members[0]).group("target")
    kind = "multi-session" if len(rigs) == 1 else "composite"
    folder = f"{target_id} {args.span} v{args.version}"
    dest = os.path.join(tpath, "integrations", folder)

    print(f"Target      : {args.target}")
    print(f"Integration : {folder}   ({kind}, {len(rigs)} rig(s))")
    print(f"Members ({len(members)}):")
    for ms in members:
        print(f"  {ms}")

    if os.path.exists(dest):
        sys.exit(f"\nERROR: integration folder already exists:\n  {dest}")

    if not args.apply:
        print(f"\nDRY RUN — nothing created. Re-run with --apply to create:\n"
              f"  integrations/{folder}/"
              f"  (PI Process/, PI Magic/, '{folder} Results/', integration.toml)")
        return

    os.makedirs(os.path.join(dest, "PI Process"))
    os.makedirs(os.path.join(dest, "PI Magic"))
    os.makedirs(os.path.join(dest, f"{folder} Results"))

    lines = [
        "# Integration manifest — see _organization/[template] integration.toml",
        "# for the documented format. Generated by new_integration.py.",
        "",
        f'kind    = "{kind}"',
        f"version = {args.version}",
        f'span    = "{args.span}"',
        "",
        "members = [",
    ]
    lines += [f'  "{ms}",' for ms in members]
    lines += [
        "]",
        "",
        "[pipeline]",
        "edited       = false",
        "published    = false",
        "printed      = false",
        'astrobin_url = ""',
        "",
        "[notes]",
        'notes = """',
        '"""',
        "",
    ]
    with open(os.path.join(dest, "integration.toml"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))

    print(f"\nCreated: {dest}")
    print("Next: build the integration in PixInsight in that folder, then "
          "re-run ingest.py.")


if __name__ == "__main__":
    main()
