#!/usr/bin/env python3
"""
new_integration.py - scaffold a living multi-session (or composite) integration.

Creates  {target}/integrations/{target_id} {rig|composite} {span}/  containing
empty PI Process/, PI Magic/ and Results/ folders, plus an integration.toml with
a rule-based [membership] section. The tracker resolves the member sessions from
that rule (rig + span) on every ingest, so the integration grows automatically as
you add nights — no member list to maintain and no version churn.

Dry run by default — it previews the sessions the rule matches today; pass
--apply to actually create the folder.

    python3 new_integration.py --target "M 81 Bodes Galaxy" \\
        --rig "RASA8 ASI2600MCAir" --span all --goal 50 --apply
    python3 new_integration.py --target "M 81 Bodes Galaxy" --span 2026     # composite
    python3 new_integration.py --target "M 81 Bodes Galaxy" --span all --apply

Then build the integration in PixInsight / PI Magic Studio inside that folder,
run mark_integrated.py to record what you stacked, and re-run ingest.py.

For a retroactive scaffold — the master already exists and contains exactly the
sessions the rule matches today — add --built to also record them in [built],
skipping the separate mark_integrated.py step. Never use --built before stacking:
[built] means "physically in the current master", and prefilling it silences the
Restack signal the empty list exists to raise.
"""

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "internal"))
import astro_config  # noqa: E402

SESSION_RE = re.compile(
    r"^(?P<target>[A-Za-z0-9_+\-]+)\s+(?P<scope>\S+)\s+(?P<sensor>\S+)\s+"
    r"(?P<date>\d{4}-\d{2}-\d{2})$"
)


def find_target(target_name, libraries):
    """Return the target folder path across the configured libraries, or None."""
    for lib in libraries:
        p = os.path.join(lib["path"], target_name)
        if os.path.isdir(p):
            return p
    return None


def span_matches(date, span):
    """True if a YYYY-MM-DD date falls within a span: '2026', '2024-2026', 'all'."""
    if span == "all":
        return True
    year = date[:4]
    m = re.fullmatch(r"(\d{4})-(\d{4})", span)
    if m:
        return m.group(1) <= year <= m.group(2)
    return year == span


def select_members(target_path, span, rig):
    """Return (members, rigs) matching the span (and rig, if given).

    Args:
        target_path: absolute path of the target folder.
        span: '2026' | a range | 'all'.
        rig: '<scope> <sensor>' to require one rig, or '' for any (composite).

    Returns:
        (sorted member folder names, set of '<scope> <sensor>' rigs seen).
    """
    members, rigs = [], set()
    for sname in sorted(os.listdir(target_path)):
        if sname == "integrations" or sname.startswith((".", "_")):
            continue
        if not os.path.isdir(os.path.join(target_path, sname)):
            continue
        m = SESSION_RE.match(sname)
        if not m or not span_matches(m.group("date"), span):
            continue
        this_rig = f"{m.group('scope')} {m.group('sensor')}"
        if rig and this_rig != rig:
            continue
        members.append(sname)
        rigs.add(this_rig)
    return members, rigs


def build_manifest(rig, span, goal_hours, built_sessions=None):
    """Render a rule-based integration.toml for a living integration.

    Args:
        rig: '<scope> <sensor>' or '' for a composite.
        span: the span string.
        goal_hours: optional integration-hours goal, or None.
        built_sessions: sessions already stacked into an existing master
            (retroactive scaffold via --built), or None for the normal
            empty [built].

    Returns:
        The manifest file contents.
    """
    lines = [
        "# Integration manifest — see tracker/templates/integration.toml",
        "# for the documented format. Generated by new_integration.py.",
        "",
        "[membership]",
        "# mode = auto: the tracker resolves members from rig + span every ingest,",
        "# so this integration grows automatically as you add nights.",
        'mode = "auto"',
    ]
    if rig:
        lines.append(f'rig  = "{rig}"          # scope+sensor; omit for a composite')
    else:
        lines.append("# rig omitted → composite (all rigs for this target/span)")
    lines.append(f'span = "{span}"')
    if goal_hours is not None:
        lines.append(f"goal_hours = {goal_hours:g}")
    lines += [
        "",
        "[built]",
        "# Sessions actually stacked into the current master. Fill this with",
        "# mark_integrated.py after each stack (or by hand).",
        "sessions = [",
    ]
    lines += [f'  "{s}",' for s in (built_sessions or [])]
    lines += [
        "]",
        "",
        "[pipeline]",
        "edited       = false",
        "published    = false",
        "printed      = false",
        'astrobin_url = ""',
        "",
        "[notes]",
        'notes = """',
        '"""',
        "",
    ]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(
        description="Scaffold a living multi-session integration folder + manifest."
    )
    ap.add_argument("--target", required=True, help="target folder name, e.g. 'M 81 Bodes Galaxy'")
    ap.add_argument("--span", required=True, help="'2026' | a range like '2024-2026' | 'all'")
    ap.add_argument(
        "--rig",
        default="",
        help="one rig 'scope sensor', e.g. 'RASA8 ASI2600MCAir'; "
        "omit for a composite across rigs",
    )
    ap.add_argument(
        "--goal",
        type=float,
        default=None,
        help="integration-hours goal for the dashboard (e.g. 50)",
    )
    ap.add_argument(
        "--built",
        action="store_true",
        help="retroactive scaffold: a master containing exactly today's "
        "matches already exists — also record them in [built] "
        "(instead of running mark_integrated.py after)",
    )
    ap.add_argument(
        "--apply", action="store_true", help="actually create the folder (default: preview only)"
    )
    ap.add_argument(
        "--config", default=None, help="path to config.toml (default: next to this script)"
    )
    args = ap.parse_args()

    libraries = astro_config.load_libraries(args.config)
    tpath = find_target(args.target, libraries)
    if not tpath:
        sys.exit(f"Target folder not found in any configured library: {args.target}")

    members, rigs = select_members(tpath, args.span, args.rig)
    if not members:
        sys.exit(
            f"No sessions matched span '{args.span}'"
            + (f" / rig '{args.rig}'" if args.rig else "")
            + f" under {args.target}."
        )

    target_id = SESSION_RE.match(members[0]).group("target")
    kind = "multi-session" if args.rig or len(rigs) == 1 else "composite"
    rig_label = args.rig if args.rig else "composite"
    folder = f"{target_id} {rig_label} {args.span}"
    dest = os.path.join(tpath, "integrations", folder)

    print(f"Target      : {args.target}")
    print(f"Integration : {folder}   ({kind}, {len(rigs)} rig(s))")
    print(
        f"Rule        : mode=auto, rig={args.rig or '(any)'}, span={args.span}"
        + (f", goal={args.goal:g}h" if args.goal is not None else "")
    )
    if args.built:
        print("Built       : retroactive — today's matches will be recorded as " "already stacked")
    print(f"Matches today ({len(members)} sessions):")
    for ms in members:
        print(f"  {ms}")

    if os.path.exists(dest):
        sys.exit(f"\nERROR: integration folder already exists:\n  {dest}")

    if not args.apply:
        print(
            f"\nDRY RUN — nothing created. Re-run with --apply to create:\n"
            f"  integrations/{folder}/  "
            f"(PI Process/, PI Magic/, '{folder} Results/', integration.toml)"
        )
        return

    os.makedirs(os.path.join(dest, "PI Process"))
    os.makedirs(os.path.join(dest, "PI Magic"))
    os.makedirs(os.path.join(dest, f"{folder} Results"))
    with open(os.path.join(dest, "integration.toml"), "w", encoding="utf-8") as fh:
        fh.write(build_manifest(args.rig, args.span, args.goal, members if args.built else None))

    print(f"\nCreated: {dest}")
    if args.built:
        print(
            f"Recorded {len(members)} session(s) in [built]. "
            "Re-run ingest.py to update the tracker."
        )
    else:
        print(
            "Next: build it in PixInsight in that folder, then run\n"
            f'  python3 mark_integrated.py "{dest}"\n'
            "and re-run ingest.py."
        )


if __name__ == "__main__":
    main()
